version: '2'
services:
  db_test:
    image: "mysql:5.7"
    hostname: "db-test"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app_test
    ports:
      - "3309:3306"
  test:
    build: .
    volumes:
      - .:/main
    depends_on:
      - db_test
